apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@github.com:aoi0412/kubernetes-infrastructure.git
    targetRevision: main
    path: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
