apiVersion: v1
data:
  sshPrivateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEci93RWNWL3pvVWVFZytYYnRCWjc4eGVSVk1nRnpkZktVNlNsNGZhM3Q5UUFBQUtCazg0V0RaUE9GCmd3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRHIvd0VjVi96b1VlRWcrWGJ0Qlo3OHhlUlZNZ0Z6ZGZLVTZTbDRmYTN0OVEKQUFBRUFiVTkwVjcwdTZ1NTV5ajU3d3cxTjZOaXgxdDcxM3FkZHhVdTlORHRCeGgrdi9BUnhYL09oUjRTRDVkdTBGbnZ6Rgo1RlV5QVhOMThwVHBLWGg5cmUzMUFBQUFHR0Z5WjI5alpFQmhjbWR2WTJRdWRHRnRZVzh1WW14MVpRRUNBd1FGCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
  url: Z2l0QGdpdGh1Yi5jb206YW9pMDQxMi9rdWJlcm5ldGVzLWluZnJhc3RydWN0dXJlLmdpdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: repo-creds
  namespace: argocd
