resources:
  - application
  - sc-pv.yaml
  - cluster.yaml
  - toolbox.yaml
patchesStrategicMerge:
  - rook-ceph-cluster-patch.yaml
  - rook-ceph-operator-toleration-patch.yaml
  - rook-ceph-rbdplugin-patch.yaml
helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: "v1.13.5"
    releaseName: rook-release
    namespace: rook-ceph
    valuesFile: values.yaml
