apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-rbdplugin
  namespace: rook-ceph
spec:
  template:
    spec:
      containers:
        - name: csi-rbdplugin
          volumeMounts:
            - name: lib-modules
              mountPath: /csi
              readOnly: true
          env:
            - name: CSI_FORCE_CEPH_KERNEL_CLIENT
              value: "true"
          securityContext:
            privileged: true
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
