apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: false
  cephVersion:
    image: ceph/ceph:v18.2.2
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  dashboard:
    enabled: true
    ssl: true
  network:
    hostNetwork: false
  crashCollector:
    disable: true
  storage:
    storageClassDeviceSets:
      - name: set1
        count: 1
        portable: false
        tuneSlowDeviceClass: true
        # 一時的に無効化
        # placement:
        #   podAntiAffinity:
        #     preferredDuringSchedulingIgnoredDuringExecution:
        #       - weight: 100
        #         podAffinityTerm:
        #           labelSelector:
        #             matchLabels:
        #               app: rook-ceph-osd
        #           topologyKey: kubernetes.io/hostname
        resources:
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 5Gi
              storageClassName: manual
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
