apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 2
    allowMultiplePerNode: false
  mgr:
    modules:
      - name: dashboard
        enabled: true
    count: 1
    standbyCount: 1
  cephVersion:
    image: ceph/ceph:v18.2.2
    allowUnsupported: false
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  dashboard:
    enabled: true
    ssl: true
  network:
    hostNetwork: false
  crashCollector:
    disable: true
  storage:
    useAllNodes: true
    useAllDevices: true
    config:
      storeType: bluestore
    storageClassDeviceSets:
      - name: set1
        count: 2
        portable: false
        tuneSlowDeviceClass: true
        placement:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: rook-ceph-osd
                  topologyKey: kubernetes.io/hostname
        resources:
        volumeClaimTemplates:
          - metadata:
              name: data
            spec:
              resources:
                requests:
                  storage: 5Gi
              storageClassName: rook-ceph-block
              volumeMode: Block
              accessModes:
                - ReadWriteOnce
