cephClusterSpec:
  storage:
    useAllNodes: true
    useAllDevices: true
    #     nodes:
    #       - name: "tama-workernode01"
    #         devices:
    #           - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
    #       - name: "tama-workernode02"
    #         devices:
    #           - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
toolbox:
  enabled: true
csi:
  rbdProvisionerResource:
    requests:
      cpu: 50m
      memory: 32Mi
  rbdPluginResource:
    requests:
      cpu: 50m
      memory: 32Mi
  cephFSProvisionerResource:
    requests:
      cpu: 50m
      memory: 32Mi
  cephFSPluginResource:
    requests:
      cpu: 50m
      memory: 32Mi
osd:
  requests:
    cpu: 50m
    memory: 128Mi
crashcollector:
  requests:
    cpu: 50m
    memory: 128Mi
