resources:
  - crds.yaml
  - common.yaml
  - operator.yaml
  - cluster.yaml
patches:
  - target:
      kind: PodSecurityPolicy
      name: 00-rook-privileged
    patch: |-
      - op: remove
        path: /apiVersion
      - op: remove
        path: /kind
      - op: remove
        path: /metadata/name
      - op: remove
        path: /spec
  - target:
      kind: ClusterRole
      name: psp:rook
    patch: |-
      - op: remove
        path: /apiVersion
      - op: remove
        path: /kind
      - op: remove
        path: /metadata/name
