apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:aoi0412/kubernetes-infrastructure.git
    targetRevision: HEAD
    path: rook-ceph
    plugin: null
    # kustomize:
    #   enableHelm: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
