### ArgoCDの設定用のファイル ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part: argocd
data:
  admin.enabled: "true"
  kustomize.buildOptions: "--enable-helm"
  # ここに他のUIや通知の設定など
  controller.cleanup.resources: |
    completedPod: true
