resources:
  - application
helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: "0.14.8"
    releaseName: metallb
    namespace: metallb-system
    valuesFile: values.yaml
