apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:aoi0412/kubernetes-infrastructure.git
    path: sealed-secret
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secret
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
